//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadTest
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Microsoft.VisualStudio.TestTools.WebTesting;
	using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


	public class FollowedCoded : WebTest
	{
		public Random rng = new Random();

		public FollowedCoded()
		{
			this.PreAuthenticate = true;
			this.Proxy = "default";
		}

		public override IEnumerator<WebTestRequest> GetRequestEnumerator()
		{
			// Initialize validation rules that apply to all requests in the WebTest
			if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
			{
				ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
				this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
			}
			if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
			{
				ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
				validationRule2.Tolerance = 0D;
				this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
			}
			var userId = rng.Next(50);
			WebTestRequest request1 = new WebTestRequest("http://localhost:14706/api/Users/" + userId +"/Followed");
			request1.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
			request1.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
			request1.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
			request1.Headers.Add(new WebTestRequestHeader("Referer", "http://localhost:14706/Home/Users"));
			yield return request1;
			request1 = null;
		}
	}
}
